just catching versions up

diff --git a/new b/new
--- a/new
+++ b/new
@@ -1,37 +1,88 @@
 #!/bin/zsh
 
+# Directory paths
+scripts_dir=$SCRIPTS
+pkm_dir=$PKMSCRIPTS
+target_dir=$scripts_dir  # Default directory
+
+# Parse command-line options
+while [[ $# -gt 0 ]]; do
+    case "$1" in
+        -p|--pkm)
+            target_dir=$pkm_dir
+            shift
+            ;;
+        -h|--help)
+            echo -e "\n[${INFO}INFO${RESET}] SUMMARY: Create/edit scripts in specified directories"
+            echo -e "\nUSAGE:"
+            echo -e "  new [options] <script-name>       Create new script"
+            echo -e "  new chmod [options] <script-name> Make script executable"
+            echo -e "\nOPTIONS:"
+            echo -e "  -p, --pkm    Use PKM scripts directory ($pkm_dir)"
+            echo -e "  -h, --help   Show this help message"
+            echo -e "\nEXAMPLES:"
+            echo -e "  new myscript          # Create in $scripts_dir"
+            echo -e "  new -p mypkm          # Create in $pkm_dir"
+            echo -e "  new chmod myscript    # Make executable in $scripts_dir"
+            echo -e "  new chmod -p mypkm    # Make executable in $pkm_dir"
+            echo
+            exit 0
+            ;;
+        *)
+            break
+            ;;
+    esac
+done
+
 arg1=$1
 arg2=$2
-scripts_pwd=$HOME/.local/scripts
 
-if [[ "$arg1" = "-h" || "$arg1" = "--help" ]]; then
-    echo "\n[${INFO}INFO${RESET}] SUMMARY: For shortcutting creating new scripts:"
-    echo "\n\tUSAGE: new [<name of new script>]"
-    echo "\n[${INFO}INFO${RESET}] Turn newly created scripts into executables:"
-    echo "\n\tUSAGE: new chmod [<name of script>]"
-    echo
-elif [[ "$arg1" = "chmod" ]]; then
-    if [[ -f "$scripts_pwd/$arg2" ]]; then
-        echo "\n[${INFO}INFO${RESET}] Turning '$arg2' into an executable file..."
-        chmod +x "$scripts_pwd/$arg2"
-        if [[ $? -eq 0 ]]; then 
-          echo "\n[${INFO}INFO${RESET}] Successfully made '$arg2' executable."
-        else
-          echo "\n[${ERROR}ERROR${RESET}] Failed to make '$arg2' executable."
+# Handle chmod command
+if [[ "$arg1" = "chmod" ]]; then
+    chmod_target=$scripts_dir  # Default to scripts directory
+    script_name=$arg2
+    
+    # Check for PKM flag in chmod
+    if [[ "$2" = "-p" || "$2" = "--pkm" ]]; then
+        chmod_target=$pkm_dir
+        script_name=$3
+        if [[ -z "$script_name" ]]; then
+            echo -e "\n[${ERROR}ERROR${RESET}] Missing script name for PKM directory"
+            exit 1
         fi
-    else
-        echo "\n[${ERROR}ERROR${RESET}] '$arg2' is not a file."
     fi
-    echo
-elif [[ -e "$scripts_pwd/$arg1" ]]; then\
-    echo "\n[${WARN}WARN${RESET}] Script: '$arg1' already exists"
-    echo "\n[${INFO}INFO${RESET}] All Scripts:"
-    ls $scripts_pwd | grep -v README.md | sed 's/^/> /'
-    echo
+
+    if [[ -f "$chmod_target/$script_name" ]]; then
+        echo -e "\n[${INFO}INFO${RESET}] Making executable: ${chmod_target/$HOME/~}/$script_name"
+        chmod +x "$chmod_target/$script_name"
+        [[ $? -eq 0 ]] && echo -e "[${INFO}SUCCESS${RESET}] Execute with: $script_name" || echo -e "[${ERROR}FAILED${RESET}]"
+    else
+        echo -e "\n[${ERROR}ERROR${RESET}] Script not found: ${chmod_target/$HOME/~}/$script_name"
+    fi
+    exit 0
+
+# Handle new script creation
+elif [[ -n "$arg1" ]]; then
+    # Check for existing script
+    if [[ -e "$target_dir/$arg1" ]]; then
+        echo -e "\n[${WARN}WARN${RESET}] Script exists: ${target_dir/$HOME/~}/$arg1"
+        echo -e "[${INFO}INFO${RESET}] Existing scripts in ${target_dir/$HOME/~}:"
+        ls -1 "$target_dir" | grep -v 'README.md' | sed "s/^/  /"
+        exit 1
+    fi
+
+    # Create new script
+    echo -e "\n[${INFO}INFO${RESET}] Creating new script in ${target_dir/$HOME/~}:"
+    echo -e "  ${INFO}$arg1${RESET}"
+    echo '#!/bin/zsh' > "$target_dir/$arg1"
+    code "$target_dir/$arg1"
+    echo -e "[${INFO}SUCCESS${RESET}] Created skeleton script. Use 'new chmod' to make executable."
+    exit 0
+
+# Handle missing arguments
 else
-    echo "\n[${INFO}INFO${RESET}] Creating a new zsh script for "$arg1...
-    echo '#!/bin/zsh' > "$scripts_pwd/$arg1"
-    echo "\n[${INFO}INFO${RESET}] Opening: " $scripts_pwd/$arg1
-    code $scripts_pwd/$arg1
-    echo
+    echo -e "\n[${ERROR}ERROR${RESET}] Missing script name"
+    echo -e "Usage: new [options] <script-name>"
+    echo -e "Try 'new --help' for more information"
+    exit 1
 fi
diff --git a/opn b/opn
--- a/opn
+++ b/opn
@@ -1,57 +1,60 @@
 #!/bin/zsh
 
-echo "Sorry I can't, I'm just a baby"
+arg1=$1
+arg2=$2
+arg3=$3
 
-# arg1=$1
-# arg2=$2
-# arg3=$3
+# Non Environment Styles
+EZAEXES="\033[38;2;178;187;103m"
 
-# if [[ "$arg1" = "-h" || "$arg1" = "--help" ]]; then
-#     echo "\n[${WARN}WARN${RESET}] For shortcutting creating new scripts:"
-#     echo "\n\tfunctionality has moved to a a script called 'new'"
-#     echo "\n[${INFO}INFO${RESET}] Available Scripts:"
-#     # ls $scripts_dir | grep -v README.md | sed 's/^/> /'
-#     ls -l $scripts_dir | grep "^-" | awk '{print $NF}'
-#     echo
-# elif [[ "$arg1" = "-n" ]]; then
-#     echo "\n[${WARN}WARN${RESET}] For shortcutting creating new scripts:"
-#     echo "\n\tfunctionality has moved to a a script called 'new'"
-#     echo
-# elif [[ "$arg1" = "new" ]]; then
-#     echo "\n[${WARN}WARN${RESET}] For shortcutting creating new scripts:"
-#     echo "\n\tfunctionality has moved to a a script called 'new'"
-#     echo
-#     echo "\n[${INFO}INFO${RESET}] Opening: " $scripts_dir/$arg1
-#     code $scripts_dir/$arg1
-#     echo
-# elif [[ -e "$scripts_dir/$arg1" ]]; then\
-#     echo "\n[${INFO}INFO${RESET}] Opening: " $scripts_dir/$arg1
-#     code $scripts_dir/$arg1
-#     echo
-# elif [[ -e "$dev_dir/$arg1" ]]; then\
-#     echo "\n[${INFO}INFO${RESET}] Opening: " $dev_dir/$arg1
-#     code $dev_dir/$arg1
-#     echo
-# elif [[ -e "$dev_dir/runs/$arg1" ]]; then\
-#     echo "\n[${INFO}INFO${RESET}] Opening: " $dev_dir/runs/$arg1
-#     code $scripts_dir/$arg1
-#     echo
-# elif [[ ! -e "$scripts_dir/$arg1" ]]; then\
-#     echo "\n[${WARN}WARN${RESET}] Script not found in: "$scripts_dir/$arg1
-#     echo
-#     echo "\n[${INFO}INFO${RESET}] Looking in: "$dev_dir/
-#     echo
-# elif [[ ! -e "$dev_dir/$arg1" ]]; then\
-#     echo "\n[${WARN}WARN${RESET}] Script not found in: "$dev_dir/$arg1
-#     echo
-#     echo "\n[${INFO}INFO${RESET}] Looking in: "$dev_dir/runs
-#     echo
-# elif [[ ! -e "$dev_dir/runs/$arg1" ]]; then\
-#     echo "\n[${ERROR}ERROR${RESET}] Script not found in: "$dev_dir/runs/$arg1
-#     echo
-#     echo "\n[${INFO}INFO${RESET}] Valid aruments include:"
-#     echo "\n[cat] [ls] [ll] [tree]\n"
-#     # ls $scripts_dir | grep -v README.md | sed 's/^/> /'
-#     ls -l $scripts_dir | grep "^-" | awk '{print $NF}'
-#     echo
-# fi
+# Define directories to search for scripts
+dirs=(
+    "$SCRIPTS"       # Primary script directory
+    "$PKMSCRIPTS"       # Obsidian script directory
+)
+
+# Handle help, new script, and legacy options
+if [[ "$arg1" = "-h" || "$arg1" = "--help" || "$arg1" = "-n" || "$arg1" = "new" || "$arg1" = "ls" ]]; then
+    echo "\n[${WARN}WARN${RESET}] For shortcutting creating new scripts:"
+    echo "\n\tFunctionality has moved to a script called 'new'"
+    [[ "$arg1" = "new" ]] && echo "\n[${INFO}INFO${RESET}] Opening: $SCRIPTS/new" && code "$SCRIPTS/new"
+    
+    echo "\n[${INFO}INFO${RESET}] Available Executable Scripts:"
+    for dir in "${dirs[@]}"; do
+        if [[ -d "$dir" ]]; then
+            echo "\n=== ${INFO}$dir${RESET} ==="
+            # Find files with execute permission, using standard tools
+            executables=$(find "$dir" -maxdepth 1 -type f -perm -u+x -exec basename {} \; 2>/dev/null | sort)
+            if [[ -n "$executables" ]]; then
+                echo "${EZAEXES}$executables${RESET}"
+            else
+                echo "No executable scripts found"
+            fi
+        else
+            echo "\n=== ${WARN}$dir (Not Found)${RESET} ==="
+        fi
+    done
+    echo
+    exit 0
+fi
+
+# Search for the script in defined directories
+found=false
+for dir in "${dirs[@]}"; do
+    if [[ -e "$dir/$arg1" ]]; then
+        echo "\n[${INFO}INFO${RESET}] Opening: $dir/$arg1"
+        code "$dir/$arg1"
+        found=true
+        break
+    fi
+done
+
+# Handle missing scripts
+if [[ "$found" == false ]]; then
+    echo "\n[${ERROR}ERROR${RESET}] Script not found in:"
+    for dir in "${dirs[@]}"; do echo "  - $dir/$arg1"; done
+    echo "\n[${INFO}INFO${RESET}] Valid arguments include:"
+    ls -l $SCRIPTS | grep "^-" | awk '{print $NF}'
+    echo
+    exit 1
+fi
